# src: https://docs.kubelinter.io/#/
# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:#1.35.0 # Specify a versioned tag
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits: # Set resource limits
        memory: "128Mi"
        cpu: "500m"
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true # Enforce a read-only root filesystem


